dictionaryDefinitions:
  - name: simcardems
    path: .cspell_dict.txt
    addWords: true
dictionaries:
  - simcardems
ignoreWords:
  [
    quickstart,
    toctree,
    maxdepth,
    genindex,
    modindex,
    mathbf,
    mathrm,
    mathbb,
    mathcal,
    operatorname,
  ]
