# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      - image: quay.io/fenicsproject/stable:latest

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install h5py --no-binary=h5py
            python3 -m pip install -e ".[dev]"

      - restore_cache:
          keys:
            - dolfin-jit-cache-pip

      - run:
          name: run pre-commit hooks
          command: |
            pre-commit run --all-files --show-diff-on-failure

      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            python3 -m pytest

      - save_cache:
          key: dolfin-jit-cache-pip
          paths:
            - ~/.cache/instant
            - ~/.cache/dijitso
            - ~/.cache/pip

      - store_artifacts:
          path: htmlcov
          destination: htmlcov

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test
