name: CI mpi

on: [push]

jobs:
  test:
    name: Run tests with in paralell
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-02-20

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
          key: cache_v5
          restore-keys: |
            cache_v5

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install h5py --no-binary=h5py
          python3 -m pip install -e ".[dev]"

      - name: Test with pytest
        run: |
          mpirun -n 2 python3 -m pytest --no-cov
