name: CI mpi

on: [push]

jobs:
  test:
    name: Run tests with in paralell
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-02-20

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install h5py --no-binary=h5py
          python3 -m pip install -e ".[dev]"

      - name: Test with pytest
        run: |
          mpirun -n 2 python3 tests/smoke.py
